<div class="c_list_side_pack">
               <a href="[field:arcurl/]" target="_blank"><img src="[field:litpic/]" alt="[field:title/]" width="65" height="65" /></a>
               <div class="c_list_side_pack_con">
                  <h5><a href="[field:arcurl/]" title="[field:title/]" target="_blank">[field:title function="cn_substr(@me,16)"/]</a></h5>[field:description function='cn_substr(@me,50)'/]...
               </div>
            </div>