<?php
$z[0]=Array("field","",136,165);
$z[0][4]['name']="typename";
$z[1]=Array("field","",218,246);
$z[1][4]['name']="typeurl";
$z[2]=Array("arclist","\r\n\r\n                  <a href=\"[field:arcurl/]\" target=\"_blank\"><img src=\"[field:litpic/]\" width=\"236\" height=\"271\" /></a>\r\n\r\n                  <h3><a href=\"[field:arcurl/]\" target=\"_blank\">[field:title/]</a></h3>\r\n\r\n                  ",442,737);
$z[2][4]['flag']="a";
$z[2][4]['row']="1";
$z[2][4]['titlelen']="34";
$z[3]=Array("arclist","\r\n\r\n                  <li><a href=\"[field:arcurl /]\">[field:title /]</a></li>\r\n\r\n                  ",872,1023);
$z[3][4]['row']="12";
$z[3][4]['titlelen']="38";
$z[4]=Array("arclist","\r\n\r\n               <div class=\"c_c_sidepic\">\r\n\r\n                  <a href=\"[field:arcurl/]\" target=\"_blank\"><img src=\"[field:litpic/]\" alt=\"[field:title/]\" width=\"156\" height=\"116\" /></a>\r\n\r\n                  <h4><a href=\"[field:arcurl/]\" title=\"[field:title/]\" target=\"_blank\">[field:title function=\"cn_substr(@me,24)\"/]</a></h4>\r\n\r\n               </div>\r\n\r\n               ",1128,1562);
$z[4][4]['flag']="c";
$z[4][4]['row']="1";
$z[4][4]['titlelen']="48";
$z[5]=Array("arclist","\r\n\r\n               <div class=\"c_c_sidepic mt10\">\r\n\r\n                  <a href=\"[field:arcurl/]\" target=\"_blank\"><img src=\"[field:litpic/]\" alt=\"[field:title/]\" width=\"156\" height=\"116\" /></a>\r\n\r\n                  <h4><a href=\"[field:arcurl/]\" title=\"[field:title/]\" target=\"_blank\">[field:title function=\"cn_substr(@me,24)\"/]</a></h4>\r\n\r\n               </div>\r\n\r\n               ",1581,2032);
$z[5][4]['flag']="c";
$z[5][4]['limit']="1,2";
$z[5][4]['row']="1";
$z[5][4]['titlelen']="48";
$z[6]=Array("arclist","\r\n\r\n            <a href=\"[field:arcurl/]\" target=\"_blank\"><img src=\"[field:litpic/]\" alt=\"[field:title/]\" width=\"156\" height=\"116\" />\r\n\r\n            <h5><a href=\"[field:arcurl/]\" title=\"[field:title/]\" target=\"_blank\">[field:title function=\"cn_substr(@me,24)\"/]</a></h5>\r\n\r\n            ",2282,2628);
$z[6][4]['flag']="b";
$z[6][4]['row']="1";
$z[6][4]['titlelen']="48";
$z[7]=Array("arclist","\r\n\r\n                  <li><a href=\"[field:arcurl/]\" target=\"_blank\">[field:title/]</a></li>\r\n\r\n                  ",2835,3020);
$z[7][4]['flag']="b";
$z[7][4]['limit']="1,9";
$z[7][4]['row']="8";
$z[7][4]['titlelen']="24";

?>