
<m:item name='基本设置' link='apps/CaiJiXia/' rank='' target='main' />
<m:item name='高级设置' link='apps/CaiJiXia/?ac=advanced' rank='' target='main' />
<m:item name='伪原创设置' link='apps/CaiJiXia/?ac=seo' rank='' target='main' />
<m:item name='搜索优化设置' link='apps/CaiJiXia/?ac=search' rank='' target='main' />
<m:item name='采集任务' link='apps/CaiJiXia/?ac=task' rank='' target='main' />
<m:item name='合作推广' link='apps/CaiJiXia/?ac=credits' rank='' target='main' />
<m:item name='插件更新' link='apps/CaiJiXia/?ac=update' rank='' target='main' />
<m:item name='帮助中心' link='http://www.dedeapps.com/Related/?plugin=caijixia' rank='' target='main' />
