<?php
if(!isset($GLOBALS['_vars'])) $GLOBALS['_vars'] = array(); 
$fields = array();
?><div id="footer" class="tl2">   <div class="footer_link">   <a href="http://www.gugeplay.com/ target=_blank" target="_blank">关于我们</a>　|　<a href="/about/ads.html" target="_blank">广告服务</a>　|　<a href="/about/copyright.html" target="_blank">版权声明</a>　|　<a href="/plus/flink.php" target="_blank">合作媒体</a>　|　<a href="/about/contact.html" target="_blank">联系我们</a>　|　<a href="/data/sitemap.html" target="_blank">网站地图</a>　|　<a href="plus/guestbook.php" target="_blank">在线留言</a>   </div>  

<p class="copyright">
		<?php echo $GLOBALS['cfg_powerby']; ?><br /><?php echo $GLOBALS['cfg_beian']; 
$atts = array();
$atts['tagname'] = 'robot';
$atts['copyright'] = 'qjpemail';
$blockValue = MakePublicTag($atts,$this->refObj,$fields); 
if(is_array($blockValue) && count($blockValue) > 0){
foreach( $blockValue as $key=>$fields )
{

}
}
?>
<div style="display: none;">
<script src="http://s111.cnzz.com/stat.php?id=427402&web_id=427402&show=pic1" language="JavaScript" charset="gb2312"></script>

</div>