<?php
$z[0]=Array("global","",384,418);
$z[0][4]['name']="cfg_basehost";
$z[1]=Array("global","",421,454);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("global","",457,494);
$z[2][4]['name']="cfg_description";
$z[3]=Array("myad","",718,747);
$z[3][4]['name']="topbanner";
$z[4]=Array("channel","\r\n\r\n         <li class=\"menu_line\"><a href='[field:typeurl/]'>[field:typename/]</a></li>",853,990);
$z[4][4]['type']="top";
$z[4][4]['row']="15";
$z[5]=Array("field","",1149,1176);
$z[5][4]['name']="phpurl";
$z[6]=Array("global","",1621,1650);
$z[6][4]['name']="cfg_templeturl";
$z[7]=Array("global","",2599,2625);
$z[7][4]['name']="cfg_dataurl";
$z[8]=Array("myad","",2829,2850);
$z[8][4]['name']="1";

?>