<?php
if(!isset($GLOBALS['_vars'])) $GLOBALS['_vars'] = array(); 
$fields = array();
?><div class="footer">
<p class="link">
		网站版权信息及免责声明
  </p>
	<!-- 
		为了支持织梦团队的发展,请您保留织梦内容管理系统的链接信息.
		我们对支持织梦团队发展的朋友表示真心的感谢!织梦因您更精彩!
	-->
	<p class="powered">
		<a href="http://www.xingi.net" target="_blank">性技巧专题知识网站</a>为你提供专业的<strong>性技巧</strong>、<strong>做爱技巧</strong>文章图片视频等，内容均来源于互联网,如有侵权,敬请联系我们,我们尽快解决!
	</p><!-- /powered -->
	
</div>