<?php
$z[0]=Array("global","",254,280);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",315,344);
$z[1][4]['name']="cfg_templeturl";
$z[2]=Array("global","",495,520);
$z[2][4]['name']="cfg_cmsurl";
$z[3]=Array("global","",523,549);
$z[3][4]['name']="cfg_webname";
$z[4]=Array("field","",616,643);
$z[4][4]['name']="phpurl";
$z[5]=Array("global","",883,905);
$z[5][4]['name']="keyword";
$z[6]=Array("global","",1354,1379);
$z[6][4]['name']="cfg_cmsurl";
$z[7]=Array("global","",1489,1518);
$z[7][4]['name']="keyword";
$z[8]=Array("list","\r\n\r\n	<div class=\"item\">\r\n		<h3><a href=\"[field:arcurl/]\" target=\"_blank\">[field:title/]</a></h3>\r\n		<p class=\"intro\">[field:description/]...</p>\r\n		<p class=\"info\">\r\n			<small>分类：</small><span> <a href=\"[field:typeurl/]\" target=\"_blank\">[field:typename/]</a></span>\r\n			<small>点击：</small><span> [field:click/]</span>\r\n			<small>日期：</small><span> [field:stime/]</span>\r\n		</p>\r\n        <p><span><a href=\"[field:arcurl/]\" target=\"_blank\">[field:arcurl/]</a></span></p>\r\n	</div>\r\n",1585,2116);
$z[8][4]['perpage']="20";
$z[9]=Array("pagelist","",2183,2212);
$z[9][4]['listsize']="5";
$z[10]=Array("likewords","",2310,2335);
$z[10][4]['num']="8";

?>