<?php
$z[0]=Array("global","",236,264);
$z[0][4]['name']="cfg_soft_lang";
$z[1]=Array("field","",277,296);
$z[1][4]['name']="title";
$z[2]=Array("global","",297,323);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("field","",364,393);
$z[3][4]['name']="keywords";
$z[4]=Array("field","",433,491);
$z[4][4]['name']="description";
$z[4][4]['function']="html2text(@me)";
$z[5]=Array("global","",509,538);
$z[5][4]['name']="cfg_templeturl";
$z[6]=Array("include","",727,762);
$z[6][4]['filename']="head.htm";
$z[7]=Array("tag","\r\n            <a href='[field:link/]' class='tagc[field:highlight /]'>[field:tag /]</a>\r\n            ",983,1125);
$z[7][4]['row']="60";
$z[7][4]['sort']="new";
$z[8]=Array("tag","\r\n            <a href='[field:link/]' class='tagc[field:highlight /]'>[field:tag /]</a>\r\n            ",1279,1423);
$z[8][4]['row']="60";
$z[8][4]['sort']="month";
$z[9]=Array("tag","\r\n            <a href='[field:link/]' class='tagc[field:highlight /]'>[field:tag /]</a>\r\n            ",1571,1715);
$z[9][4]['row']="100";
$z[9][4]['sort']="rand";
$z[10]=Array("include","",1758,1795);
$z[10][4]['filename']="footer.htm";

?>