<?php
$myaddons = array();
$maNum = 0;
$myaddons[$maNum] = array('458', '/index/uploads/allimg/120304/5_120304185142_1.jpg');
$maNum = 1;
$myaddons[$maNum] = array('459', '/index/uploads/allimg/120304/5_120304185621_1.jpg');
$maNum = 2;
$myaddons[$maNum] = array('460', '/index/uploads/allimg/120304/5_120304185728_1.jpg');
$maNum = 3;
$myaddons[$maNum] = array('461', '/index/uploads/allimg/120304/5_120304185817_1.jpg');
$maNum = 4;
$myaddons[$maNum] = array('462', '/index/uploads/allimg/120304/5_120304190001_1.jpg');
$maNum = 5;
