<?php
$myaddons = array();
$maNum = 0;
$myaddons[$maNum] = array('443', '/index/uploads/allimg/120224/5_120224111303_1.jpg');
$maNum = 1;
$myaddons[$maNum] = array('444', '/index/uploads/allimg/120224/5_120224114424_1.jpg');
$maNum = 2;
$myaddons[$maNum] = array('445', '/index/uploads/allimg/120224/5_120224114506_1.jpg');
$maNum = 3;
$myaddons[$maNum] = array('446', '/index/uploads/allimg/120224/5_120224114543_1.jpg');
$maNum = 4;
$myaddons[$maNum] = array('447', '/index/uploads/allimg/120224/5_120224114727_1.jpg');
$maNum = 5;
$myaddons[$maNum] = array('448', '/index/uploads/allimg/120224/5_120224115044_1.gif');
$maNum = 6;
$myaddons[$maNum] = array('449', '/index/uploads/allimg/120224/5_120224115125_1.jpg');
$maNum = 7;
