<?php
$myaddons = array();
$maNum = 0;
$myaddons[$maNum] = array('194', '/index/uploads/allimg/110307/4_110307122101_1.jpg');
$maNum = 1;
$myaddons[$maNum] = array('195', '/index/uploads/allimg/110307/4_110307122101_3.jpg');
$maNum = 2;
$myaddons[$maNum] = array('196', '/index/uploads/allimg/110307/4_110307122421_1.jpg');
$maNum = 3;
$myaddons[$maNum] = array('197', '/index/uploads/allimg/110307/4_110307122655_1.jpg');
$maNum = 4;
