<?php
$myaddons = array();
$maNum = 0;
$myaddons[$maNum] = array('656', '/index/uploads/allimg/120608/5_120608171739_1.jpg');
$maNum = 1;
$myaddons[$maNum] = array('657', '/index/uploads/allimg/120608/5_120608172206_1.jpg');
$maNum = 2;
$myaddons[$maNum] = array('658', '/index/uploads/allimg/120608/5_120608172252_1.jpg');
$maNum = 3;
$myaddons[$maNum] = array('659', '/index/uploads/allimg/120608/5_120608172544_1.jpg');
$maNum = 4;
