<?php
$myaddons = array();
$maNum = 0;
$myaddons[$maNum] = array('450', '/index/uploads/allimg/120224/5_120224123333_1.jpg');
$maNum = 1;
$myaddons[$maNum] = array('451', '/index/uploads/allimg/120224/5_120224124202_1.jpg');
$maNum = 2;
$myaddons[$maNum] = array('452', '/index/uploads/allimg/120224/5_120224124708_1.jpg');
$maNum = 3;
$myaddons[$maNum] = array('453', '/index/uploads/allimg/120224/5_120224125037_1.jpg');
$maNum = 4;
$myaddons[$maNum] = array('454', '/index/uploads/allimg/120224/5_120224125941_1.jpg');
$maNum = 5;
$myaddons[$maNum] = array('455', '/index/uploads/allimg/120224/5_120224130701_1.jpg');
$maNum = 6;
