<?php
$myaddons = array();
$maNum = 0;
$myaddons[$maNum] = array('651', '/index/uploads/allimg/120608/5_120608115223_1.jpg');
$maNum = 1;
$myaddons[$maNum] = array('652', '/index/uploads/allimg/120608/5_120608115225_2.jpg');
$maNum = 2;
$myaddons[$maNum] = array('653', '/index/uploads/allimg/120608/5_120608115226_3.jpg');
$maNum = 3;
$myaddons[$maNum] = array('654', '/index/uploads/allimg/120608/5_120608120718_1.jpg');
$maNum = 4;
$myaddons[$maNum] = array('655', '/index/uploads/allimg/120608/5_120608120718_2.jpg');
$maNum = 5;
