<?php
$myaddons = array();
$maNum = 0;
$myaddons[$maNum] = array('636', '/index/uploads/allimg/120519/5_120519192914_1.jpg');
$maNum = 1;
$myaddons[$maNum] = array('637', '/index/uploads/allimg/120519/5_120519192918_1.jpg');
$maNum = 2;
$myaddons[$maNum] = array('638', '/index/uploads/allimg/120519/5_120519192929_1.jpg');
$maNum = 3;
$myaddons[$maNum] = array('639', '/index/uploads/allimg/120519/5_120519192929_2.jpg');
$maNum = 4;
$myaddons[$maNum] = array('640', '/index/uploads/allimg/120519/5_120519193138_1.jpg');
$maNum = 5;
$myaddons[$maNum] = array('641', '/index/uploads/allimg/120519/5_120519193142_2.jpg');
$maNum = 6;
